[build]
  command = ""
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "live-server --port=3000 --no-browser --watch=public ./public/"
  port = 8888
  targetPort = 3000
  publish = "public"